apiVersion: v1
kind: Service
metadata:
  name: preview-service
  namespace: cse474-prod
  labels:
    app: preview-service
spec:
  type: ClusterIP
  selector:
    app: preview-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
