apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backup.name }}-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.backup.service.port | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  DB_USER: {{ .Values.postgres.user | quote }}
  BACKUP_DB_HOST: {{ .Values.postgres.backupHost | quote }}
  KAFKA_BROKER: {{ .Values.kafka.broker | quote }}
