apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.analytics.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.analytics.service.type }}
  ports:
  - port: {{ .Values.analytics.service.port }}
    targetPort: {{ .Values.analytics.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.analytics.name }}
