apiVersion: apps/v1
kind: Deployment
metadata:
  name: compression-service
  namespace: cse474-prod
  labels:
    app: compression-service
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compression-service
  template:
    metadata:
      labels:
        app: compression-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3002"
    spec:
      containers:
        - name: compression-service
          image: m91011/compression-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
              name: http

          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          envFrom:
            - configMapRef:
                name: services-config

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: COMPRESSION_PORT
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: COMPRESSION_SERVICE_NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COMPRESSION_DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COMPRESSION_DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COMPRESSION_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COMPRESSION_DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COMPRESSION_DB_PASS
            - name: KAFKA_GROUP_ID
              value: "compression-service-group"
